### ISSUE TITLE
License file missing?

### ISSUE THREAD

**Issue by JustGitting** [e-radionicacom/Inkplate-6-Arduino-library#1]
Hi,

Just wondering if you have selected the FOSS license for the project yet. I suggest you use a copy-left license to protect users from developers (not necessarily you good people :) ) from taking away the freedom from users to run, study, modify and distribute the software. For example I'd suggest the GPLv3.

Cheers

**Comment by davidzovko** [comment]
Thanks, [license](https://github.com/e-radionicacom/Inkplate-6-Arduino-library/blob/master/LICENSE) has been added!
