### ISSUE TITLE
Calendar example

### ISSUE THREAD

**Issue by fibis** [e-radionicacom/Inkplate-6-Arduino-library#13]
Would it be possible to add also the calendar example (https://www.crowdsupply.com/img/56ab/demo-calendar_png_content-body-gallery.jpg)?

**Comment by davidzovko** [comment]
It's work in progress, should be ready by end of this week!

**Comment by davidzovko** [comment]
Added: https://github.com/e-radionicacom/Inkplate-6-Arduino-library/tree/master/examples/3.%20Projects/4-Google_calendar_example
