### ISSUE TITLE
Which zip file should I install to use this library?

### ISSUE THREAD

**Issue by skybrian** [e-radionicacom/Inkplate-6-Arduino-library#14]
I don't know the format for an Arduino library. If I check out this repo using git, can I use it directly? If I need a zip file, does it contain the repo zipped up or is it created in some other way?

**Comment by davidzovko** [comment]
Hey Brian. You can just download the whole ZIP of this repo and install it into Arduino. We have a small tutorial on it, check it out: https://e-radionica.com/en/blog/arduino-library/#Kako%20instaliraty%20library?

**Comment by skybrian** [comment]
Okay, thanks! Cloning the repo works for me.

It seems like the directions should be explicit that it's the .zip file in the "Code" menu for the repo.
