### ISSUE TITLE
Fonts/Roboto_Light_48.h: No such file or directory

### ISSUE THREAD

**Issue by JoergWende** [e-radionicacom/Inkplate-6-Arduino-library#26]
I try to compile the daily weather station example and it results in:
Fonts/Roboto_Light_48.h: No such file or directory

Any hint ?

**Comment by nitko12** [comment]
What IDE are you using, in the example there's a directory containing custom fonts and Arduino, by default, includes it.

**Comment by JoergWende** [comment]
third restart of the arduino toolkit resolved the issue.
Thanks !

**Comment by markhen57** [comment]
I had this issue after I saved the example to another sketch for my modifications - you need to copy the "Fonts" folder from the example folder to the destination sketch folder!
