### ISSUE TITLE
icons.h - includes binary_icons/icon_c.h

### ISSUE THREAD

**Issue by JoergWende** [e-radionicacom/Inkplate-6-Arduino-library#27]
but the files are not here - where to get them ?
Cheers
J.

**Comment by nitko12** [comment]
Possibly the same issue as your [previous](https://github.com/e-radionicacom/Inkplate-6-Arduino-library/issues/26), can you supply more info and check is there a folder binary_icons in the example sketch folder.

**Comment by JoergWende** [comment]
Arduino 1.8.13
Third restart of the toolkit resolved the problem - thanks
