### ISSUE TITLE
A few new install issues

### ISSUE THREAD

**Issue by rseymour** [e-radionicacom/Inkplate-6-Arduino-library#31]
Hello,

Just installing my inkplate now getting ready to do the first example.

First 2 issues, there are no .zip downloads for the Sdfat and Inkplate 6 Arduino library, that seems to be solvable with:

```
wget https://github.com/e-radionicacom/Inkplate-6-SDFat-Arduino-Library/archive/master.zip -O sdfat.zip
```

and

```
wget https://github.com/e-radionicacom/Inkplate-6-Arduino-library/archive/master.zip -O inkplate.zip
```

Doing such downloads from the GUI is a bit more involved, but may be eased by having a 'release' for each.

My current issue seems to be pythonic in nature.

```
Arduino: 1.8.13 (Linux), Board: "Inkplate 6(ESP32), Enabled, Huge APP (3MB No OTA), 240MHz (WiFi/BT), 115200, None"











Traceback (most recent call last):
  File "/home/rseymour/.arduino15/packages/Croduino_Boards/tools/esptool_py/2.6.0/esptool.py", line 35, in <module>
    import serial.tools.list_ports as list_ports
ImportError: No module named serial.tools.list_ports
Multiple libraries were found for "WiFiClient.h"
 Used: /home/rseymour/.arduino15/packages/Croduino_Boards/hardware/esp32/1.0.0/libraries/WiFi
 Not used: /home/rseymour/Downloads/arduino-1.8.13/libraries/WiFi
exit status 1
Error compiling for board Inkplate 6(ESP32).
```

Not sure why it's not reaching out to the esptool for py2, but it is.

At any rate, this can be solved by installing pip2 (via: curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py) and installing esptool (which installs the right pyserial) for py2 instead of py3)

This could be solved somehow by doing some work on py2 py3 compatibility I believe, but I really hate that transition so I can understand if you don't want to do any changes.

After that everything works, so this issue is more for documentation through suffering than an actual issue.

**Comment by nitko12** [comment]
Hi, 
thanks for reaching out over your issue!

How exactly are you flashing your Inkplate, Arduino CLI or something?
I haven't worked on the board definitions, they are calling Python2 if I understand you correctly?
I believe it calls whatever python is under default python command?

What should we change to make it less a hassle installing on systems as such? :)

**Comment by niklasnisbeth** [comment]
I had the same Python2 issue. I installed pyserial via my distro's package manager and that fixed it. Maybe you can update the blog entry to list it as a dependency, or put it in the README.

**Comment by martinberlin** [comment]
Just wanted to add my 0.2 cents here. If at any point you want to use PlatformIO (VSCode) to compile this:
https://github.com/e-radionicacom/Inkplate-6-Arduino-library/issues/16#issuecomment-667026408

I left there link to a repository that should install all libraries automatically.

**Comment by rseymour** [comment]
I would say the variety of python2/3 setups folks might have is always tough to guess before the fact.  I would put the dependency in there.  I used the arduino IDE to flash, IIRC, but the python deps were kind of hidden by that.  Either way I got it working for what I wanted, so I'm happy.  It's a very cool piece of hardware.
