### ISSUE TITLE
Where did the weather go?

### ISSUE THREAD

**Issue by jf1452** [e-radionicacom/Inkplate-6-Arduino-library#35]
Hi,

I was looking forward to playing with the weather and calendar examples; but the links don't work; and there are no longer any arduino examples; did I look in the wrong place?

Cheers

Jon

**Comment by davidzovko** [comment]
Hi Jon, you can find those in the "dev" branch. We are working on some changes to the library, so we had to remove those. It will be back to master branch soon!

**Comment by jf1452** [comment]
Thank you so much David! very fast response. I'll take a look.

**Comment by jf1452** [comment]
Hi David, I got it now; I see you're not far away :) I'm just over the border near Ivancna Gorica! When there are no restrictions I love going to Hrelic

**Comment by davidzovko** [comment]
Well not that much close, but Hrelić is widely know :) - we are located in Osijek, at the east of Croatia. 

Let us know if you need any other kind of help!
