### ISSUE TITLE
PNG from web always draws at 0,0

### ISSUE THREAD

**Issue by jf1452** [e-radionicacom/Inkplate-6-Arduino-library#43]
I really like the new updated libraries; I am using the new options to create an OpenWeatherOnceCall based weather display (the weather display example does not have many cities).
I'm using the code...

    sprintf(Output,"http://openweathermap.org/img/wn/%s@4x.png",OWOC.current.owicon);
    Serial.print(Output);
    display.drawImage(Output, 100, 100, true, true);
    
    for (int day = 0; day < 7; day++)
    {
      sprintf(Output,"http://openweathermap.org/img/wn/%s@2x.png",OWOC.forecast[day].owicon);
      Serial.print(Output);
      display.drawImage(Output, 100 + (day * 200), 400, true, true);
    }

Irrespective of the X,Y locations, all images are drawn at 0,0.

**Comment by nitko12** [comment]
Here's the fix, 

https://github.com/e-radionicacom/Inkplate-6-Arduino-library/commit/4144390c15f95a7dc140dccf7ce2bf4013916aca

Thanks for reporting the bug :D
