### ISSUE TITLE
Solder bridges?  Where are they

### ISSUE THREAD

**Issue by svwhisper** [e-radionicacom/Inkplate-6-Arduino-library#6]
Example 8-Inkplate_MCP23017_expander.ino refers to solder bridges.  I cannot see anything on the pcb near the touch pad area that looks like a solder bridge, but perhaps my eyes are just not good enough.  Where are these, please?

**Comment by davidzovko** [comment]
Hey, sorry for not documenting this better. Please check the picture below:

![Back](https://user-images.githubusercontent.com/12273484/88278440-ab7d1d00-cce2-11ea-998b-eb65c18d3331.JPG)

Hope this helps! Let me know if I can help more with this.

**Comment by davidzovko** [comment]
Closing issue since no further questions.
